### ISSUE TITLE
Write a Python notebook to generate a trajectory matrix

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/single-cell-pathway-analysis#15]
For a given normalized single-cell transcriptomic matrix, and two groups of cells, this file will generate a trajectory matrix.

A trajectory matrix provides random walk flows between each pair of cells, but only the subset of the flows that reach the target(s).

Reuse the code in random_walk.ipynb, but keep the notebook part as short as possible and encapsulate isolatable parts in functions.

**Comment by kinali** [comment]
For a given normalized single-cell transcriptomic matrix, and two groups of cells, generate_traj_matrix.ipynb generates subset flow matrix and writes that matrix containing cell labels as dataframe by calling the functions in random_walk_helper_functions.py
